<?php

namespace SisGG\FinalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoVentaRepository extends EntityRepository{
    
    //Devuelve todas las categorias que no tienen ningun padre asociado
    public function findByNombres($tag) {
        return $this->getEntityManager()
                        ->createQuery("SELECT p FROM SisGGFinalBundle:ProductoVenta p WHERE (upper(p.nombre) LIKE upper(:tag))")
                        ->setParameter('tag', '%'.$tag.'%')
                        ->getResult();
    }
    
    public function findByEstadoActivo() {
        return $this->getEntityManager()
                        ->createQuery("SELECT p FROM SisGGFinalBundle:ProductoVenta p WHERE p.activo = true")
                        ->getResult();
    }
    
    public function findByIds($productos) {
        if ($productos!=null){
        return $this->getEntityManager()
                        ->createQuery("SELECT p FROM SisGGFinalBundle:ProductoVenta p WHERE p.id IN (?1)")
                        ->setParameter(1, $productos)
                        ->getResult();
        }else{
            return $this->getEntityManager()
                        ->createQuery("SELECT p FROM SisGGFinalBundle:ProductoVenta p WHERE p.id = 0")
                        ->getResult();
        }
    }
}
