<?php

namespace SisGG\FinalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RedireccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedireccionRepository extends EntityRepository {
    
    public function findRedirecciones($unUsuario){
        return $this->getEntityManager()
                        ->createQuery("SELECT r FROM SisGGFinalBundle:Redireccion r WHERE r.usuarioA = ?1 and r.visto=false")
                        ->setParameter(1, $unUsuario)
                        ->getResult();
    }
    
}
